# Generated by Django 3.1 on 2021-05-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'employee'), ('director', 'director')], max_length=13, verbose_name='role'),
        ),
    ]
