# Generated by Django 3.1 on 2021-04-19 05:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file_ky',
            field=models.FileField(blank=True, null=True, upload_to='document', verbose_name='документ'),
        ),
        migrations.AddField(
            model_name='news',
            name='file_ru',
            field=models.FileField(blank=True, null=True, upload_to='document', verbose_name='документ'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_ky',
            field=models.CharField(max_length=3000, null=True, verbose_name='Под заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='subtitle_ru',
            field=models.CharField(max_length=3000, null=True, verbose_name='Под заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ky',
            field=models.CharField(max_length=3000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=3000, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='news',
            name='video_ky',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='video_ru',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
