# Generated by Django 3.1 on 2021-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210419_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentorganizationcategory',
            name='category_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименовение категории'),
        ),
        migrations.AddField(
            model_name='contentorganizationcategory',
            name='category_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Наименовение категории'),
        ),
    ]
