# Generated by Django 3.1 on 2021-04-19 10:37

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210419_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentorganizationcategory',
            options={'verbose_name': 'Категория организации контента', 'verbose_name_plural': 'Категория организации контента'},
        ),
        migrations.RemoveField(
            model_name='contentorganization',
            name='data_cr',
        ),
        migrations.AddField(
            model_name='contentorganization',
            name='category_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to_content', to='webapp.contentorganizationcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='contentorganization',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_to_content', to='webapp.contentorganizationcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='contentorganization',
            name='img_ky',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='contentorganization',
            name='img_ru',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='фото'),
        ),
        migrations.AddField(
            model_name='contentorganization',
            name='text_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='contentorganization',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='contentorganization',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='contentorganization',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='contentorganization',
            name='video_ky',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на фидео'),
        ),
        migrations.AddField(
            model_name='contentorganization',
            name='video_ru',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на фидео'),
        ),
        migrations.AlterField(
            model_name='contentorganization',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
