# Generated by Django 3.1 on 2021-04-21 04:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210419_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentorganization',
            options={'verbose_name': 'Контент организации', 'verbose_name_plural': 'Контент организации'},
        ),
        migrations.RemoveField(
            model_name='contentorganization',
            name='category_ky',
        ),
        migrations.RemoveField(
            model_name='contentorganization',
            name='category_ru',
        ),
        migrations.AddField(
            model_name='categorynpa',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория НПА'),
        ),
        migrations.AddField(
            model_name='categorynpa',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Категория НПА'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='title_ky',
            field=models.CharField(max_length=500, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='leadership',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='npa',
            name='document_type_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='Вид документа'),
        ),
        migrations.AddField(
            model_name='npa',
            name='document_type_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Вид документа'),
        ),
        migrations.AddField(
            model_name='npa',
            name='file_ky',
            field=models.FileField(null=True, upload_to='doc', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='npa',
            name='file_ru',
            field=models.FileField(null=True, upload_to='doc', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='npa',
            name='subtitle_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='Под зоголовок'),
        ),
        migrations.AddField(
            model_name='npa',
            name='subtitle_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Под зоголовок'),
        ),
        migrations.AddField(
            model_name='npa',
            name='text_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='npa',
            name='text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='npa',
            name='title_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголово'),
        ),
        migrations.AddField(
            model_name='npa',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Заголово'),
        ),
        migrations.AddField(
            model_name='organizationstructure',
            name='title_ky',
            field=models.CharField(max_length=500, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='organizationstructure',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='npa',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
