# Generated by Django 3.1 on 2021-04-21 14:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210421_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=300, null=True, verbose_name='Заголовок')),
                ('data', models.DateField(verbose_name='Дата')),
                ('text', ckeditor.fields.RichTextField()),
                ('text_ru', ckeditor.fields.RichTextField(null=True)),
                ('text_ky', ckeditor.fields.RichTextField(null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='boc', verbose_name='Файл')),
                ('file_ru', models.FileField(blank=True, null=True, upload_to='boc', verbose_name='Файл')),
                ('file_ky', models.FileField(blank=True, null=True, upload_to='boc', verbose_name='Файл')),
                ('data_cr', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Объявления',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.AlterModelOptions(
            name='categorynpa',
            options={'verbose_name': 'Категория НПА', 'verbose_name_plural': 'Категория НПА'},
        ),
        migrations.AlterModelOptions(
            name='categoryoc',
            options={'verbose_name': 'Категория ОС', 'verbose_name_plural': 'Категория ОС'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='corruption',
            options={'verbose_name': 'Антикоррупционная деятельность', 'verbose_name_plural': 'Антикоррупционная деятельность'},
        ),
        migrations.AlterModelOptions(
            name='corruptioncategory',
            options={'verbose_name': 'Категория антикоррупционной деятельности', 'verbose_name_plural': 'Категория антикоррупционной деятельности'},
        ),
        migrations.AlterModelOptions(
            name='directory',
            options={'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочник'},
        ),
        migrations.AlterModelOptions(
            name='leadership',
            options={'verbose_name': 'Руковотство', 'verbose_name_plural': 'Руковотство'},
        ),
        migrations.AlterModelOptions(
            name='npa',
            options={'verbose_name': 'НПА', 'verbose_name_plural': 'Категория НПА'},
        ),
        migrations.AlterModelOptions(
            name='organizationstructure',
            options={'verbose_name': 'Структура организации', 'verbose_name_plural': 'Структура организации'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Положение', 'verbose_name_plural': 'Положение'},
        ),
        migrations.AlterModelOptions(
            name='recommendationoc',
            options={'verbose_name': 'Рекомендации ОС', 'verbose_name_plural': 'Рекомендации ОС'},
        ),
        migrations.AlterModelOptions(
            name='regulationsoc',
            options={'verbose_name': 'Нормативно-правовые акты', 'verbose_name_plural': 'Нормативно-правовые акты'},
        ),
        migrations.AlterModelOptions(
            name='structureoc',
            options={'verbose_name': 'Состав ОС', 'verbose_name_plural': 'Состав ОС'},
        ),
        migrations.AlterModelOptions(
            name='study',
            options={'verbose_name': 'Исследования', 'verbose_name_plural': 'Исследования'},
        ),
        migrations.AlterModelOptions(
            name='sur',
            options={'verbose_name': 'ЦУР', 'verbose_name_plural': 'ЦУР'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вкансии', 'verbose_name_plural': 'Вкансии'},
        ),
        migrations.AddField(
            model_name='position',
            name='description_ky',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='structure',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='structure',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='study',
            name='author_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='study',
            name='author_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='study',
            name='directions_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='study',
            name='directions_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='study',
            name='document_type_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='Вид документа'),
        ),
        migrations.AddField(
            model_name='study',
            name='document_type_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Вид документа'),
        ),
        migrations.AddField(
            model_name='study',
            name='file_ky',
            field=models.FileField(null=True, upload_to='study', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='study',
            name='file_ru',
            field=models.FileField(null=True, upload_to='study', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='study',
            name='name_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование Файла'),
        ),
        migrations.AddField(
            model_name='study',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Наименование Файла'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
