# Generated by Django 3.1 on 2021-04-22 11:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210421_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Категория')),
                ('name_ru', models.CharField(max_length=300, null=True, verbose_name='Категория')),
                ('name_ky', models.CharField(max_length=300, null=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория вакансии',
                'verbose_name_plural': 'Категория вакансии',
            },
        ),
        migrations.AlterModelOptions(
            name='npa',
            options={'verbose_name': 'НПА', 'verbose_name_plural': 'НПА'},
        ),
        migrations.RenameField(
            model_name='structureoc',
            old_name='Position',
            new_name='position',
        ),
        migrations.AddField(
            model_name='categoryoc',
            name='name_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='categoryoc',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_ky',
            field=models.CharField(max_length=100, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='corruption',
            name='document_type_ky',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип токумента'),
        ),
        migrations.AddField(
            model_name='corruption',
            name='document_type_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип токумента'),
        ),
        migrations.AddField(
            model_name='corruption',
            name='file_ky',
            field=models.FileField(null=True, upload_to='doc', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='corruption',
            name='file_ru',
            field=models.FileField(null=True, upload_to='doc', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='corruption',
            name='title_ky',
            field=models.CharField(max_length=400, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='corruption',
            name='title_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='corruptioncategory',
            name='name_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='corruptioncategory',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='directory',
            name='title_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='Организации'),
        ),
        migrations.AddField(
            model_name='directory',
            name='title_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Организации'),
        ),
        migrations.AddField(
            model_name='recommendationoc',
            name='file_ky',
            field=models.FileField(null=True, upload_to='OC', verbose_name='Фаил'),
        ),
        migrations.AddField(
            model_name='recommendationoc',
            name='file_ru',
            field=models.FileField(null=True, upload_to='OC', verbose_name='Фаил'),
        ),
        migrations.AddField(
            model_name='recommendationoc',
            name='name_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='recommendationoc',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='regulationsoc',
            name='description_ky',
            field=models.CharField(max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='regulationsoc',
            name='description_ru',
            field=models.CharField(max_length=400, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='regulationsoc',
            name='file_ky',
            field=models.FileField(null=True, upload_to='OC', verbose_name='Фаил'),
        ),
        migrations.AddField(
            model_name='regulationsoc',
            name='file_ru',
            field=models.FileField(null=True, upload_to='OC', verbose_name='Фаил'),
        ),
        migrations.AddField(
            model_name='structureoc',
            name='position_ky',
            field=models.CharField(max_length=300, null=True, verbose_name='Должность и место работы'),
        ),
        migrations.AddField(
            model_name='structureoc',
            name='position_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Должность и место работы'),
        ),
        migrations.AddField(
            model_name='sur',
            name='file_ky',
            field=models.FileField(null=True, upload_to='doc', verbose_name='файл'),
        ),
        migrations.AddField(
            model_name='sur',
            name='file_ru',
            field=models.FileField(null=True, upload_to='doc', verbose_name='файл'),
        ),
        migrations.AddField(
            model_name='sur',
            name='title_ky',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='sur',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='file_ky',
            field=models.FileField(blank=True, null=True, upload_to='doc', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='file_ru',
            field=models.FileField(blank=True, null=True, upload_to='doc', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='text_ky',
            field=models.CharField(max_length=3000, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='text_ru',
            field=models.CharField(max_length=3000, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ky',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contacts',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='directory',
            name='contacts',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
