# Generated by Django 3.1 on 2021-04-30 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0007_auto_20210422_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='director',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_news', to=settings.AUTH_USER_MODEL, verbose_name='director'),
        ),
        migrations.AddField(
            model_name='news',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='employee'),
        ),
        migrations.AddField(
            model_name='npa',
            name='director',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_npa', to=settings.AUTH_USER_MODEL, verbose_name='director'),
        ),
        migrations.AddField(
            model_name='npa',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='employee'),
        ),
        migrations.AddField(
            model_name='study',
            name='director',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_study', to=settings.AUTH_USER_MODEL, verbose_name='director'),
        ),
        migrations.AddField(
            model_name='study',
            name='employee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='employee'),
        ),
    ]
